'use strict';
let previewData=null, previewDefinition='', selected=new Set(), importing=false, stopRequested=false, reviewed=null, uiRevision=0;
const localLists=['languages','exclude_languages','genres','exclude_genres'];
const localNumbers=['year_min','year_max','rating_min'];
function readLocalFilters(){const out={};for(const k of localLists){const v=el('local_'+k).value.split(',').map(x=>x.trim()).filter(Boolean);if(v.length)out[k]=v;}for(const k of localNumbers){if(el('local_'+k).value!=='')out[k]=Number(el('local_'+k).value);}if(el('local_keep_unknown').checked)out.keep_unknown=true;return out;}
function readExcluded(){const text=el('excludedIds').value.trim();if(!text)return [];const ids=text.split(',').map(x=>Number(x.trim()));if(ids.some(x=>!Number.isSafeInteger(x)||x<=0))throw Error('Excluded IDs must be comma-separated positive integers.');return [...new Set(ids)];}
function loadLocalFilters(f){for(const k of localLists)el('local_'+k).value=(f.local_filters?.[k]||[]).join(', ');for(const k of localNumbers)el('local_'+k).value=f.local_filters?.[k]??'';el('local_keep_unknown').checked=!!f.local_filters?.keep_unknown;el('excludedIds').value=(f.exclude_ids||[]).join(', ');}
function invalidatePreview(){uiRevision++;previewData=null;selected.clear();el('visualPreview').hidden=true;el('importSettings').hidden=true;reviewed=null;if(el('addReview').open)el('addReview').close();}
function target(){return previewData?.media==='movies'?'radarr':'sonarr';}
function updateSelection(){el('previewSummary').textContent=`${previewData.items.length} titles · ${selected.size} selected. Select cards for a one-time add, or exclude titles and save the feed.`;for(const checkbox of el('posterGrid').querySelectorAll('input[type=checkbox]'))checkbox.checked=selected.has(Number(checkbox.dataset.id));}
function renderCards(){posterObserver.disconnect();el('posterGrid').replaceChildren();for(const item of previewData.items){const card=document.createElement('article');card.className='card';card.dataset.id=item.id;const cover=document.createElement('div');cover.className='cover';cover.textContent='No poster available';setupPoster(cover,item,previewData.media,previewData.tmdb_enabled);const body=document.createElement('div');body.className='card-body';const select=document.createElement('input');select.type='checkbox';select.dataset.id=item.id;select.setAttribute('aria-label',`Select ${item.title}`);select.onchange=()=>{if(select.checked)selected.add(item.id);else selected.delete(item.id);updateSelection();};const label=document.createElement('label');label.append(select,document.createTextNode(' Select'));const title=document.createElement('h3');title.textContent=item.title;const meta=document.createElement('p');meta.textContent=[item.year??'Year unknown',item.language||'Language unknown',item.network,item.rating==null?null:`★ ${item.rating.toFixed(1)}`].filter(Boolean).join(' · ');body.append(label,title,meta);for(const [name,url]of Object.entries(item.links)){const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=name;body.append(link);}if(item.overview){const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Overview';const text=document.createElement('p');text.textContent=item.overview;detail.append(summary,text);body.append(detail);}const exclude=document.createElement('button');exclude.type='button';exclude.textContent='Exclude';exclude.onclick=()=>excludeTitles([item.id]);const add=document.createElement('button');add.type='button';add.textContent='Add…';add.onclick=()=>action(async()=>{if(el('importSettings').hidden)await loadImporterSettings();reviewAdd([item.id]);});body.append(exclude,add);card.append(cover,body);el('posterGrid').append(card);}updateSelection();}
async function loadPreview(){const revision=uiRevision,definition=readFeed(true);const data=await api('/api/preview/cards',definition);if(revision!==uiRevision)return;previewData=data;previewDefinition=JSON.stringify(definition);selected.clear();el('importResults').hidden=true;el('visualPreview').hidden=false;el('importSettings').hidden=true;const json=data.items.map(x=>data.media==='movies'?{id:x.id,title:x.title}:{tvdbId:x.id,title:x.title});el('results').textContent=JSON.stringify(json,null,2);el('results').hidden=false;renderCards();status(`${data.items.length} titles returned. Posters load from Trakt, with optional TMDB fallback.`);try{const available=await api('/api/importers');if(revision!==uiRevision)return;el('importAvailability').textContent=available[target()]?`${target()} is configured. Load its profiles and root folders to add titles.`:`Set ${target().toUpperCase()}_URL and ${target().toUpperCase()}_API_KEY in the container to enable direct adds.`;}catch(e){if(revision===uiRevision)el('importAvailability').textContent=e.message;}}
function excludeTitles(ids){try{el('excludedIds').value=[...new Set([...readExcluded(),...ids])].join(', ');invalidatePreview();status('Exclusions updated. Preview again to refill the list, then save to update its URL.');}catch(e){status(e.message);}}
async function loadImporterSettings(){if(!previewData)throw Error('Preview titles first.');const sid=previewData.preview_id,t=target();const data=await api(`/api/importers/${t}/options`);if(previewData?.preview_id!==sid)throw Error('Preview changed. Load settings again.');options(el('qualityProfile'),[['','Choose profile'],...data.profiles.map(p=>[p.id,p.name])]);options(el('rootFolder'),[['','Choose root folder'],...data.roots.map(p=>[p,p])]);el('importLegend').textContent=`Add to ${t}`;el('seriesTypeField').hidden=t!=='sonarr';el('availabilityField').hidden=t!=='radarr';el('importSettings').hidden=false;el('directImport').open=true;}
function importSettings(){if(!el('qualityProfile').value||!el('rootFolder').value)throw Error('Choose a quality profile and root folder.');if(el('searchAdded').checked&&!el('monitorAdded').checked)throw Error('Enable monitoring before download searching.');return {quality_profile_id:Number(el('qualityProfile').value),root_folder:el('rootFolder').value,monitored:el('monitorAdded').checked,search:el('searchAdded').checked,series_type:el('seriesType').value,minimum_availability:el('minimumAvailability').value};}
function reviewAdd(ids){if(importing)throw Error('An add is already running.');if(!previewData||JSON.stringify(readFeed(true))!==previewDefinition)throw Error('Settings changed. Preview again first.');if(!ids.length)throw Error('Select at least one title.');reviewed={preview_id:previewData.preview_id,target:target(),ids:[...ids],settings:importSettings(),items:previewData.items.filter(x=>ids.includes(x.id))};el('reviewTitle').textContent=`Add ${ids.length} ${ids.length===1?'title':'titles'} to ${reviewed.target}?`;el('reviewSettings').textContent=`${el('qualityProfile').selectedOptions[0].textContent} · ${reviewed.settings.root_folder} · Monitoring ${reviewed.settings.monitored?'on':'off'} · Download search ${reviewed.settings.search?'on':'off'}. Existing titles will be skipped.`;el('reviewTitles').replaceChildren();for(const item of reviewed.items){const li=document.createElement('li');li.textContent=`${item.title}${item.year?' ('+item.year+')':''}`;el('reviewTitles').append(li);}el('addReview').showModal();}
function freezeUI(on){for(const element of document.querySelectorAll('input,select,textarea,button')){if(element.id==='stopAdding')continue;if(on){element.dataset.wasDisabled=element.disabled?'1':'0';element.disabled=true;}else{element.disabled=element.dataset.wasDisabled==='1';delete element.dataset.wasDisabled;}}}
async function runAdd(){if(!reviewed||importing)return;const plan=reviewed;reviewed=null;el('addReview').close();importing=true;stopRequested=false;freezeUI(true);el('stopAdding').hidden=false;el('importResults').textContent='';el('importResults').hidden=false;let done=0;try{for(let offset=0;offset<plan.ids.length&&!stopRequested;offset+=10){const data=await api(`/api/importers/${plan.target}/add`,{preview_id:plan.preview_id,ids:plan.ids.slice(offset,offset+10),settings:plan.settings});for(const result of data.results){el('importResults').textContent+=`${result.title}: ${result.status}${result.message?' — '+result.message:''}\n`;done++;if(result.status==='unknown')stopRequested=true;}status(`Processed ${done}/${plan.ids.length}.`);}status(stopRequested?`Stopped after ${done}/${plan.ids.length}. Review the results before retrying.`:`Finished ${done} titles. See per-title results below.`);}catch(e){status(`${e.message} Stopped without retrying. Check the target library before retrying; the last batch may have completed.`);}finally{freezeUI(false);importing=false;el('stopAdding').hidden=true;}}
el('feedForm').addEventListener('input',()=>{if(!importing)invalidatePreview();});
el('feedForm').addEventListener('change',()=>{if(!importing)invalidatePreview();});
el('connect').addEventListener('click',invalidatePreview);
el('selectAll').onclick=()=>{selected=new Set(previewData.items.map(x=>x.id));updateSelection();};
el('selectNone').onclick=()=>{selected.clear();updateSelection();};
el('excludeSelected').onclick=()=>excludeTitles([...selected]);
el('loadImporter').onclick=()=>action(loadImporterSettings);
el('addSelected').onclick=()=>{try{reviewAdd([...selected]);}catch(e){status(e.message);}};
el('addAll').onclick=()=>{try{reviewAdd(previewData.items.map(x=>x.id));}catch(e){status(e.message);}};
el('cancelAdd').onclick=()=>{reviewed=null;el('addReview').close();};
el('confirmAdd').onclick=runAdd;
el('stopAdding').onclick=()=>{stopRequested=true;status('Stopping after the current batch completes.');};

const posterObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){posterObserver.unobserve(entry.target);entry.target.loadArtwork?.();}},{rootMargin:'200px'});
function setupPoster(cover,item,media,enabled){
 let triedFallback=false;
 async function fallback(){if(triedFallback||!enabled||!item.ids.tmdb)return;triedFallback=true;try{const data=await api(`/api/poster/${media}/${item.ids.tmdb}`);if(data.poster&&cover.isConnected)display(data.poster);}catch{/* Keep placeholder; feed remains usable. */}}
 function display(url){const image=document.createElement('img');image.alt=`${item.title} poster`;image.referrerPolicy='no-referrer';image.onerror=()=>{cover.textContent='No poster available';fallback();};image.src=url;cover.replaceChildren(image);}
 cover.loadArtwork=()=>{if(item.poster)display(item.poster);else fallback();};posterObserver.observe(cover);
}
